In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 50, 10)

In [3]:
arr

array([35,  2, 14, 31, 28, 21, 10, 10, 36, 17], dtype=int32)

In [4]:
arr[0:5]

array([35,  2, 14, 31, 28], dtype=int32)

In [5]:
arr[5:]

array([21, 10, 10, 36, 17], dtype=int32)

In [6]:
arr[0:5] = 100

In [7]:
arr

array([100, 100, 100, 100, 100,  21,  10,  10,  36,  17], dtype=int32)

In [8]:
arr[:] = 99

In [9]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99], dtype=int32)

In [10]:
arr_2d =np.array([[5,10,15], [20,25,30],[35,40,45]])

In [11]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [12]:
arr_2d[0]

array([ 5, 10, 15])

In [13]:
arr_2d[2]

array([35, 40, 45])

In [14]:
arr_2d[-1]

array([35, 40, 45])

In [15]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [16]:
arr =np.arange(1,11)

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
bool_arr = arr>4

In [19]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [20]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [21]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])