In [1]:
import numpy as np

In [5]:
my_list = [1,2,3]

In [6]:
type(my_list)

list

In [7]:
mmy_array = np.array(my_list)

In [8]:
type(mmy_array)

numpy.ndarray

In [9]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [10]:
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [11]:
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.eye(4)  #Identity Matrix|

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])