In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [6]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr.sum()

np.int64(45)

In [8]:
int(arr.sum())

45

In [9]:
arr.min()

np.int64(0)

In [10]:
int(arr.min())

0

In [11]:
int(arr.min())

0

In [12]:
int(arr.max())

9

In [13]:
arr.var()

np.float64(8.25)

In [14]:
int(arr.var())

8

In [15]:
arr.std()

np.float64(2.8722813232690143)

In [16]:
arr2d = np.arange(25).reshape(5,5)

In [17]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
arr2d.sum(axis= 0)

array([50, 55, 60, 65, 70])

In [19]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])