In [1]:
import numpy as np

In [2]:
np.random.rand(1)

array([0.30989419])

In [ ]:
np.random.randn(10)  #random numbers from normal distribution

array([-0.48457799,  0.25389441, -3.51302298, -2.99258078,  1.22225755,
       -0.21418388, -0.64211839,  1.22625986,  1.5070965 , -0.52869802])

In [ ]:
np.random.randint(0, 101, 5)


array([23, 91, 25, 59, 48], dtype=int32)

In [5]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [6]:
ranarr = np.random.randint(1, 101, 10)

In [7]:
ranarr

array([ 83,  87,  75,  75,  88, 100,  24,   3,  22,  53], dtype=int32)

In [8]:
ranarr.max()

np.int32(100)

In [9]:
ranarr.argmax()

np.int64(5)

In [10]:
ranarr.min()

np.int32(3)

In [11]:
ranarr.argmin()

np.int64(7)